services:
  postgres:
    image: postgres:16
    container_name: aspci_postgres
    environment:
      POSTGRES_USER: harry
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    ports:
      - '15432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

