services:
  postgres:
    image: postgres:16
    container_name: aspci_postgres
    environment:
      POSTGRES_USER: harrydev
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    ports:
      - '15432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped
volumes:
  redis-data: